name: Flake Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  matrix-checks:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    env:
      NIX_CONFIG: access-tokens = github.com=${{ secrets.NIX_GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: home linux laptop
            runner: ubuntu-latest
            command: nix build .#homeConfigurations.laptop.activationPackage --show-trace --print-build-logs
          - name: home linux desktop
            runner: ubuntu-latest
            command: nix build .#homeConfigurations.desktop.activationPackage --show-trace --print-build-logs
          - name: home darwin macbook_air
            runner: macos-14
            command: nix build .#homeConfigurations.macbook_air.activationPackage --show-trace --print-build-logs
          - name: nixos dev_thinkpad
            runner: ubuntu-latest
            command: nix build .#nixosConfigurations.dev_thinkpad.config.system.build.toplevel --show-trace --print-build-logs
          - name: nixos desktop
            runner: ubuntu-latest
            command: nix build .#nixosConfigurations.desktop.config.system.build.toplevel --show-trace --print-build-logs
          - name: darwin macbook_air
            runner: macos-14
            command: nix build .#darwinConfigurations.macbook_air.system --show-trace --print-build-logs
          - name: global flake check
            runner: ubuntu-latest
            command: nix flake check --show-trace --print-build-logs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Run check
        run: ${{ matrix.command }}
